owner: c4ad
repo: uptime-tool

sites:
  - name: Fitwel Portal Front-End
    url: https://app.fitwel.org
  - name: Fitwel Portal Back-End
    url: https://api.fitwel.org/health
    method: GET
  - name: E-mail Notification Service
    url: https://adai.app.n8n.cloud
  - name: Fitwel VPN Services
    url: https://vpn.fitwel.fitwel.org

status-website:
  cname: statuspage.fitwel.org
  logoUrl: https://images.squarespace-cdn.com/content/v1/6294f761bc48c512bfad618b/0eb45243-5c6c-4a63-b1f0-38efc7493465/Fitwel+Logo+Website+Black.png?format=1500w
  name: Fitwel Portal Status Hub
  introTitle: Your One-Stop Shop for Fitwel Portal Health
  introMessage: Hey there! 👋 Stay in the loop with real-time updates on our system status.
  navbar:
    - title: Home Base
      href: /
    - title: Jump Back to Portal
      href: https://app.fitwel.org
  theme: light

i18n:
  footer: Developed by [Fitwel Engineering Team](https://fitwel.org), powered by [ADAI](https://adai.com)
